language: bash
services: docker

env:
  - VERSION=centos6
  - VERSION=centos7
  - VERSION=fedora22
  - VERSION=fedora23

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - export image="quay.io/stackstorm/rpmbuildpack-deps:$VERSION"

script:
  - docker build -t "$image-curl" curl
  - docker build -t "$image-scm" scm
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
